project:
  type: website
  output-dir: docs

website:
  title: "MID PROJECT"
  description: "A Seven-Decade Analysis of Trends and Influences"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: projects.qmd
        text: "Projects"
      - href: Code.qmd
        text: "Source Code"
      - href: References.qmd
        text: "References"
      - href: contact.qmd
        text: "Contact"
      


format:
  html:
    theme: darkly
    toc: true



