project:
  type: website

website:
  title: "ANNAM KAVYA"
  description: "Data ENGINEER | Developer | Researcher"
  navbar:
    right:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: projects.qmd
        text: "Projects"
      - href: contact.qmd
        text: "Contact"

format:
  html:
    output_dir: docs
    theme: cerulean
    toc: true



