---
title: "About Us"
description: "Learn more about our background, skills, and experiences."
format:
  html:
    execute:
      warning:false
    output_dir: docs
---

# Hi, I'm Annam Kavya 👋

## About me

I am a **Systems Engineer** and **Senior Software Engineer** with 5 years of experience in the IT industry. I have led data engineering efforts for Aviva Health UK, designing scalable data pipelines and implementing comprehensive ETL processes. My expertise includes managing databases like Oracle, Hive, and Snowflake, and enhancing reporting capabilities with Qlik Sense.To further enhance my skills, I am currently pursuing a Master's in Data Analytics at George Mason University. When I'm not working, I enjoy hiking and photography, which help me stay creative and inspired.

## My Skill Set

-   **Languages**: SQL, Python, R
-   **Data Engineering**:
    -   ETL processes, data pipeline design
-   **Databases**:
    -   Oracle, Hive, Snowflake
-   **Big Data Technologies**:
    -   Apache Spark, Apache Kafka, Databricks
-   **Reporting Tools**:
    -   Power BI, Tableau, Qlik Sense

## Experience

### Senior Software Engineer \| LTI Mindtree

-   Designed ETL data load strategies and translated complex business requirements into effective data models.
-   Implemented documentation standards and best practices for ETL mappings.

### Systems Engineer \| Tata Consultancy Services

-   Led data engineering efforts for Aviva Health UK, designing scalable data pipelines and implementing ETL processes.
-   Managed and optimized databases to ensure data quality and performance.

# Hi, I'm Bhavya Sri 👋

## About me

I embarked on a journey where data meets healthcare, combining my technical skills with a passion for improving health outcomes. With a Bachelor's degree in Computer Science Engineering from India, I've always been driven by a passion for data architecture and healthcare data analytics. This passion led me across the globe to George Mason University, where I'm currently pursuing a Master's in Data Analytics. Through this project, I blend my technical skills with a love for making sense of complex data, all with the aim of improving health outcomes. Come along as we navigate the world of lung cancer data and uncover insights that could pave the way for a healthier future.

## My Skill Set

-   **Languages**: SQL, Python, R
-   **Reporting Tools**:
-   Power BI, Tableau, Qlik Sense

## My Intrests

-   Data Architecture
-   Health Data Analytics
-   Social Service
-   Badminton

