---
title: "References"
format: html
editor: visual
---
1.  **Tableau**. (n.d.). *Data visualization tips*. Retrieved October 8, 2024, from <https://www.tableau.com/learn/articles/data-visualization-tips>

2.  **Chartexpo**. (n.d.). *Misleading charts: How to spot and fix misleading visualizations*. Retrieved October 8, 2024, from <https://chartexpo.com/blog/misleading-charts>

3.  **Wickham, H., Chang, W., Henry, L., Pedersen, T. L., Takahashi, K., Wilke, C., Woo, K., & Yutani, H.** (n.d.). *ggplot2: Create elegant data visualisations using the grammar of graphics*. GitHub. Retrieved October 8, 2024, from <https://github.com/tidyverse/ggplot2/blob/HEAD/R/theme-defaults.R>

4.  **Kassambara, A.** (n.d.). *GGPlot2 themes and background colors* \[Webpage\]. Retrieved October 8, 2024, from <http://www.sthda.com/english/wiki/ggplot2-themes-and-background-colors-the-3-elements>

5.  **Johan**. (n.d.). *World countries GeoJSON data* \[Data file\]. GitHub. Retrieved October 8, 2024, from <https://github.com/johan/world.geo.json>

6.  **National Center for Health Statistics**. (n.d.). *Lung cancer incidence and mortality data* \[Data set\]. Retrieved October 8, 2024, from <https://ourworldindata.org/grapher/lung-cancer-deaths-per-100000-by-sex-1950-2002?time=earliest..latest>

7.  **National Center for Health Statistics**. (n.d.). *Lung cancer trends* \[Data visualization\]. Retrieved October 8, 2024, from <https://ourworldindata.org/grapher/lung-cancer-deaths-per-100000-by-sex-1950-2002?time=earliest..latest>

8.  **Wickham, H., Chang, W., Henry, L., Pedersen, T. L., Takahashi, K., Wilke, C., Woo, K., & Yutani, H.** (2024). *ggplot2: Create elegant data visualisations using the grammar of graphics* (Version 3.4.2) \[R package\]. Retrieved from <https://cran.r-project.org/web/packages/ggplot2/index.html>

9.  **Wickham, H., François, R., Henry, L., & Müller, K.** (2024). *dplyr: A grammar of data manipulation* (Version 1.1.2) \[R package\]. Retrieved from <https://cran.r-project.org/web/packages/dplyr/index.html>

10. **Wickham, H., Hester, J., & Bryan, J.** (2024). *readr: Read rectangular text data* (Version 2.1.4) \[R package\]. Retrieved from <https://cran.r-project.org/web/packages/readr/index.html>

11. **Müller, K., & Wickham, H.** (2024). *tibble: Simple data frames* (Version 3.2.1) \[R package\]. Retrieved from <https://cran.r-project.org/web/packages/tibble/index.html>

12. **Sievert, C.** (2024). *plotly: Create interactive web graphics via 'plotly.js'* (Version 4.10.2) \[R package\]. Retrieved from <https://cran.r-project.org/web/packages/plotly/index.html>

13. **Chang, W., Cheng, J., Allaire, J. J., Sievert, C., Schloerke, B., Xie, Y., Allen, J., McPherson, J., Dipert, A., & Borges, B.** (2024). *Shiny: Web application framework for R* (Version 1.7.5) \[R package\]. Retrieved from <https://cran.r-project.org/web/packages/shiny/index.html>

14. **Neuwirth, E.** (2024). *RColorBrewer: ColorBrewer palettes* (Version 1.1-3) \[R package\]. Retrieved from <https://cran.r-project.org/web/packages/RColorBrewer/index.html>

15. **Pedersen, T. L.** (2024). *gganimate: A grammar of animated graphics* (Version 1.8.0) \[R package\]. Retrieved from <https://cran.r-project.org/web/packages/gganimate/index.html>

16.**Zoom**. (2020, March 26). *How to record a Zoom meeting* \[Video\]. YouTube. Retrieved October 8, 2024, from <https://www.youtube.com/watch?v=H9qhoAIzW3E>
